spring:
  application:
    name: customerportal
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  backoffice:
    base-url: ${BACKOFFICE_BASE_URL:http://localhost:5000}
    api-key: ${BACKOFFICE_API_KEY:dev-key}
    timeout-ms: 5000