ALTER TABLE pickup_request
ALTER COLUMN length_cm TYPE INTEGER USING ROUND(length_cm)::INTEGER,
    ALTER COLUMN width_cm  TYPE INTEGER USING ROUND(width_cm)::INTEGER,
    ALTER COLUMN height_cm TYPE INTEGER USING ROUND(height_cm)::INTEGER;