CREATE TABLE region (
                        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code         VARCHAR(16)  NOT NULL,
                        city         VARCHAR(100) NOT NULL,
                        country_code VARCHAR(2)      NOT NULL,
                        timezone     VARCHAR(64)  NOT NULL,

                        CONSTRAINT uq_region_code UNIQUE (code),
                        CONSTRAINT ck_region_country_code CHECK (country_code ~ '^[A-Z]{2}$')
    );

CREATE INDEX idx_region_country_code ON region (country_code);

CREATE TABLE route (
                       id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       route_type VARCHAR(20)  NOT NULL,
                       multiplier NUMERIC(4,2) NOT NULL,

                       CONSTRAINT uq_route_route_type UNIQUE (route_type),
                       CONSTRAINT ck_route_route_type
                           CHECK (route_type IN ('SAME_CITY', 'SAME_COUNTRY', 'CROSS_COUNTRY')),
                       CONSTRAINT ck_route_multiplier_positive CHECK (multiplier > 0)
);




CREATE TABLE service_rate (
                              id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              service_type                  VARCHAR(20)   NOT NULL,
                              base_price                    NUMERIC(10,2) NOT NULL,
                              per_kg_rate                   NUMERIC(10,2) NOT NULL,
                              surcharge_amount              NUMERIC(10,2) NOT NULL DEFAULT 0,
                              surcharge_weight_threshold_kg NUMERIC(6,2),
                              order_cut_off_time            TIME,
                              min_time_before_slot_minutes  INTEGER,
                              cross_country_allowed         BOOLEAN       NOT NULL DEFAULT TRUE,

                              CONSTRAINT uq_service_rate_service_type UNIQUE (service_type),
                              CONSTRAINT ck_service_rate_service_type
                                  CHECK (service_type IN ('STANDARD', 'EXPRESS', 'SAME_DAY')),
                              CONSTRAINT ck_service_rate_base_price  CHECK (base_price  >= 0),
                              CONSTRAINT ck_service_rate_per_kg_rate CHECK (per_kg_rate >= 0),
                              CONSTRAINT ck_service_rate_surcharge   CHECK (surcharge_amount >= 0),
                              CONSTRAINT ck_service_rate_lead_time   CHECK (min_time_before_slot_minutes >= 0),

                              CONSTRAINT ck_service_rate_surcharge_pair CHECK (
                                  (surcharge_amount = 0 AND surcharge_weight_threshold_kg IS NULL)
                                      OR (surcharge_amount > 0 AND surcharge_weight_threshold_kg IS NOT NULL)
                                  )
);

INSERT INTO route (route_type, multiplier) VALUES
                                               ('SAME_CITY',     1.00),
                                               ('SAME_COUNTRY',  1.20),
                                               ('CROSS_COUNTRY', 1.80);

INSERT INTO region (code, city, country_code, timezone) VALUES
                                                            ('HU-BUD', 'Budapest',   'HU', 'Europe/Budapest'),
                                                            ('HU-DEB', 'Debrecen',   'HU', 'Europe/Budapest'),
                                                            ('HU-SZE', 'Szeged',     'HU', 'Europe/Budapest'),
                                                            ('AT-VIE', 'Vienna',     'AT', 'Europe/Vienna'),
                                                            ('AT-GRZ', 'Graz',       'AT', 'Europe/Vienna'),
                                                            ('CZ-PRG', 'Prague',     'CZ', 'Europe/Prague'),
                                                            ('CZ-BRN', 'Brno',       'CZ', 'Europe/Prague'),
                                                            ('PL-WAW', 'Warsaw',     'PL', 'Europe/Warsaw'),
                                                            ('PL-KRK', 'Krakow',     'PL', 'Europe/Warsaw'),
                                                            ('DE-BER', 'Berlin',     'DE', 'Europe/Berlin'),
                                                            ('SK-BTS', 'Bratislava', 'SK', 'Europe/Bratislava');



INSERT INTO service_rate (
    service_type, base_price, per_kg_rate,
    surcharge_amount, surcharge_weight_threshold_kg,
    order_cut_off_time, min_time_before_slot_minutes, cross_country_allowed
) VALUES
      ('STANDARD',   5.00, 1.50,  2.00, 10.00, NULL,    NULL, TRUE),
      ('EXPRESS',   12.00, 2.50,  5.00, 10.00, NULL,     120, TRUE),
      ('SAME_DAY',  25.00, 4.00, 10.00,  5.00, '10:00', NULL, FALSE);