name: Add issue to project
on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Add to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Swift-Parcel/projects/5
          github-token: ${{ steps.app-token.outputs.token }}